### ISSUE TITLE
Character encoding issue

### ISSUE THREAD

**Issue by BriceSchaffner** [mesilat/confluence-fields#1]
I have a confluence server that is configured to use UTF-8 encoding and uses special characters like äöü. On Jira the webwork.i18n.encoding is also configured as UTF-8, but the "System Encoding" is configured to Cp1252. The problem is that if I refer to pages with special characters they are not displayed correctly.
In the example below the Confluence page have the following title: **_2109 Lütschine-Gsteig_** 
But it get displayed as "2109 LÃ¼tschine-Gsteig" in Jira.
![image](https://user-images.githubusercontent.com/28617124/58474951-dc98a680-814c-11e9-94ae-d30006ab446e.png)

**Comment by mesilat** [comment]
Hi,
The JIRA docs recommend using utf-8 for System Encoding. I believe that the issue roots to class com.atlassian.sal.api.net.Response method getResponseBodyAsString:

`
private DataServiceResult execute(ApplicationLinkRequest request) throws ResponseException {
        return request.execute(new ApplicationLinkResponseHandler<DataServiceResult>() { 
            @Override 
            public DataServiceResult handle(com.atlassian.sal.api.net.Response response) throws ResponseException {
                LOGGER.debug(String.format("Response from remote server: code=%d", response.getStatusCode()));
                return new DataServiceResult(response.getStatusCode(), response.getResponseBodyAsString());
            } 
        });
    }
`
but I am not sure. Do you have an advice on how to fix this issue?

**Comment by BriceSchaffner** [comment]
Hi

I could solve the issue by changing the JIRA System Encoding to UTF-8 (adding the Java options _-Dfile.encoding=utf-8_). I also set the Application Server URL encoding to UTF-8 (added _URIEncoding="UTF-8"_ attribute in the _Connector_ element of the server.xml file).
See also https://confluence.atlassian.com/jirakb/jira-application-internationalisation-and-encoding-troubleshooting-203394762.html
