### ISSUE TITLE
cant use field on kanban board

### ISSUE THREAD

**Issue by Yasharah** [mesilat/confluence-fields#10]
Hello,

the plugin is working like a charm on the normal issues view, but we cant fill in any information into it when we are trying to do that from the kanban board Issue Detail View. You can click on the field, but the search doesn't work. If you still enter something, the field will be displayed as if it now had content, but it is shown as empty.

attempt to write something into the field with search function not working:
![kanban_issue_view](https://user-images.githubusercontent.com/30473222/71094612-8dc76280-21ab-11ea-86e4-8d0c70f51e0e.png)

empty field on normale issue view:
![normal_issue_view_with_empty_field](https://user-images.githubusercontent.com/30473222/71094611-8dc76280-21ab-11ea-9d59-c39beed0be75.png)

**Comment by mesilat** [comment]
Hi,
Thanks for reporting the issue.I will investigate the problem and publish a solution is a couple of days.
Regards,
Vladislav Babin
Mesilat Limited

**Comment by mesilat** [comment]
Hi,
Please check version 1.0.19 It should fix the issue
Regards

**Comment by akrapivin** [comment]
1.0.20 reintroduced this issue

**Comment by mesilat** [comment]
Sorry, please upgrade to 1.0.21 and let me know if this fixes the issue.

In latest JIRA Atlassian's decided to remove underscore-1.4.4 library. Currently it provides underscore-1.5.2 and underscore-1.8.3 supplied with GH-plugin. I decided to package my own underscore version with the plugin which appeared to cause problems with GH.

**Comment by mesilat** [comment]
Hi, @akrapivin 

Did v1.0.21 fix your issue?

**Comment by akrapivin** [comment]
@mesilat yes, the issue is fixed.
