### ISSUE TITLE
Error 500 on confluence field

### ISSUE THREAD

**Issue by jllaurado** [mesilat/confluence-fields#11]
I have just installed the plugin and I find REST requests that fail with error 500:

http://metis.fiberpachs.com/jira/rest/confield/1.0/field/11600/pages?q=searchparam&max-results=10&filter-fields=%7B%7D&_=1578393101427

I'm searching for 'searchparam' but the server says that the path doesn't exist.

What I'm doing wrong? The installation is automated and there is no configuration on either the custom field or the plugin itself.

**Comment by mesilat** [comment]
Hi,
Please take a look at docs: https://www.mesilat.com/pages/jira/confluence-fields/
confluence field should be configured to work properly
