### ISSUE TITLE
Add the ability to add "Issue links" to confluence.

### ISSUE THREAD

**Issue by tbe** [mesilat/confluence-fields#12]
Currently there is no usefull way from confluence to see which issues refer to a given confluence page.

If there is no issue yet, we get an JQL error (page could not be found), and no incoming issue link will be added to the page meta.

**Comment by mesilat** [comment]
Thanks for reporting. This should be fixed in v 1.0.22

**Comment by mesilat** [comment]
Hi, @tbe 

Did v1.0.22 fix the issue?

**Comment by tbe** [comment]
Des, it did. Thank you for the quick response and fix 

Am 27. Februar 2020 16:51:27 MEZ schrieb Mesilat Limited <notifications@github.com>:
>Hi, @tbe 
>
>Did v1.0.22 fix the issue?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/mesilat/confluence-fields/issues/12#issuecomment-592030896

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
