### ISSUE TITLE
Cannot search pages with access restrictions

### ISSUE THREAD

**Issue by akrapivin** [mesilat/confluence-fields#15]
Confluence pages with access restrictions are not displayed even if the current user has access rights to this pages

**Comment by mesilat** [comment]
Hi, thanks for reporting.

Are you using definer rights or current user rights in your Confluence field settings? If definer rights are used than the definer user should have access rights to a Confluence page for it to be listed in JIRA.

You can use REST API browser to check if Confluence lists your content properly. The Confluence custom fields plugin uses `/rest/api/content/search?cql=<cql>&limit=<limit>` endpoint to get a list of pages from Confluence. Take a look at `DataServiceImpl.findPages` method at https://github.com/mesilat/confluence-fields/blob/master/confluence-fields-plugin/src/main/java/com/mesilat/confield/DataServiceImpl.java

**Comment by mesilat** [comment]
No feedback from reporter. Closing

**Comment by akrapivin** [comment]
Hi, sorry for delayed response
After quick investigation I've found that this is a bug https://jira.atlassian.com/browse/CONFSERVER-36393 - Confluence simply doesn't search across restricted pages at all. Could you mention this in documentation?
