### ISSUE TITLE
Ticket creations page no longer closes

### ISSUE THREAD

**Issue by zstetinova** [mesilat/confluence-fields#16]
Hallo,
After activating Plugin Confluence Custom Fields the following behavior can be observed:
Jira Service Desk doesn´t work whit Internet Explorer - Warning:
{"xsrfToken":"B4W7-X2D7-LD66-RHKC_fbf905e6a9cec37483cf9007e58a954628ebe7fa_lout","helpCenterBranding":{"headerBGColor":"#141e32","headerLinkColor":"#ffffff","headerLinkHoverColor":"#141e32","headerLinkHoverBGColor":"#ffffff","logoUrl":"","helpCenterTitle":"REICHHART digital logistics - Servicedesk","sharedPortalName":"Servicedesk"},"login":{"allowCookies":true,"externalUserManagement":true,"contactAdminLink":"wenden Sie sich bitte an Ihre Jira Administratoren","elevatedSecurityCheckShown":false,"loginUrl":"/servicedesk/customer/user/login","canReset":false,"sdUserSignUpEnabled":false,"loginAnnouncementHeader":"","loginAnnouncementMessage":""},"loginAnnouncement":{"header":"","headerWiki":"","message":"","messageWiki":"","canEditAnnouncement":false,"portalId":null}}

{"tourEnabled":false,"wacLink":"https://www.atlassian.com/software/jira/service-desk/powered-by?utm_medium=jira-in-product&utm_source=jira_service_desk_portal_footer&utm_campaign=service-desk_portal_server","serviceDeskVersion":"4.2.2","contextPath":"","xsrfToken":"B4W7-X2D7-LD66-RHKC_fbf905e6a9cec37483cf9007e58a954628ebe7fa_lout","baseUrl":"https://jira-test.reichhart.eu/servicedesk/customer","relativeBaseUrl":"/servicedesk/customer","customerLoginEnabled":true,"maxAttachmentSize":"20971520","gravatarEnabled":false,"calendarDateData":{"months":["Januar","Februar","März","April","Mai","Juni","Juli","August","September","Oktober","November","Dezember"],"monthsShort":["Jan","Feb","Mär","Apr","Mai","Jun","Jul","Aug","Sep","Okt","Nov","Dez"],"weekdaysShort":["So","Mo","Di","Mi","Do","Fr","Sa"],"weekdays":["Sonntag","Montag","Dienstag","Mittwoch","Donnerstag","Freitag","Samstag"]}}

Im Chrome, after creating a new ticket in the Servicedesk Portal, the page is not continued after the Finish button. The circle on the side does not stop spinning. Ticket is created normally and also appears in the Jira. After Deaktivating the Plugin, Problems disappear.  Browser logs attached. 

Best Regards
Zlatica

![image](https://user-images.githubusercontent.com/57717260/78671776-0596d580-78e0-11ea-8a49-1288cd7ab45f.png)

**Comment by mesilat** [comment]
Hi, Zlatica
Thanks for reporting an issue. 

As for the second issue: the information you provided is not enough to start investigation. Please specify the version of SD you are using.

As for the first issue: IE is not and will never be supported, sorry.

**Comment by zstetinova** [comment]
Hi, 
SD Version is 4.2.2 (IE - I understand:-))

BR 
Zlatica

**Comment by mesilat** [comment]
Hi, Zlatica

Sorry for delay. I have tested the plugin with JSD 4.2.2 (as well as some later versions) but could not reproduce the error you reported. Meanwhile I did some refactoring to get a more extensive browser-side trace log and fixed some bugs that may have (or may have not) caused the problem you described. Could you please upgrade to version 1.0.25 and tell me if this fixes the issue?

If not then I will need all the trace log you could collect by using the following procedure:

- open browser console and enable the plugin trace log by running the following command:
```
window.localStorage['CFP_TRACE_ENABLED'] = true
```
Please use console filter to search for lines matching "confluence-fields" only. Reproduce the error then copy and paste all the log here.

You may later disable trace by running:
```
delete window.localStorage['CFP_TRACE_ENABLED']
```
<img width="1149" alt="Screenshot 2020-04-24 at 13 06 50" src="https://user-images.githubusercontent.com/18350871/80201297-971a7d00-862c-11ea-9c05-bd26a0695418.png">

Best regards,
Valdislav

**Comment by zstetinova** [comment]
Hallo Vladimir,
here the Logs
window.localStorage['CFP_TRACE_ENABLED'] = true
true
batch.js?locale=de-DE:361 confluence-fields confluence-fields::updatefields() {atl_token: "B4W7-X2D7-LD66-RHKC_30068a7048ecf84170fc6704fa8776f6865a9ab7_lin", projectId: "11100", undefined: "", reporter: "zstetinova", summary: "Test", …} {}
batch.js?locale=de-DE:361 confluence-fields portal::initPortalFields()
batch.js?locale=de-DE:361 confluence-fields portal::getIssue(): jsonPayload {xsrfToken: "B4W7-X2D7-LD66-RHKC_30068a7048ecf84170fc6704fa8776f6865a9ab7_lin", user: {…}, branding: {…}, helpCenterBranding: {…}, portal: {…}, …}
batch.js?locale=de-DE:361 confluence-fields portal::initPortalFields()
batch.js?locale=de-DE:361 confluence-fields portal::getIssue(): jsonPayload {xsrfToken: "B4W7-X2D7-LD66-RHKC_30068a7048ecf84170fc6704fa8776f6865a9ab7_lin", user: {…}, branding: {…}, helpCenterBranding: {…}, portal: {…}, …}
batch.js?locale=de-DE:361 confluence-fields portal::initPortalFields()
batch.js?locale=de-DE:361 confluence-fields portal::getIssue(): jsonPayload {xsrfToken: "B4W7-X2D7-LD66-RHKC_30068a7048ecf84170fc6704fa8776f6865a9ab7_lin", user: {…}, branding: {…}, helpCenterBranding: {…}, portal: {…}, …}
batch.js?locale=de-DE:361 confluence-fields confluence-fields::updatefields() {atl_token: "B4W7-X2D7-LD66-RHKC_30068a7048ecf84170fc6704fa8776f6865a9ab7_lin", projectId: "11100", undefined: "", reporter: "zstetinova", summary: "Test", …} {}
batch.js?locale=de-DE:361 confluence-fields portal::initPortalFields()
batch.js?locale=de-DE:361 confluence-fields portal::getIssue(): jsonPayload {xsrfToken: "B4W7-X2D7-LD66-RHKC_30068a7048ecf84170fc6704fa8776f6865a9ab7_lin", user: {…}, branding: {…}, helpCenterBranding: {…}, portal: {…}, …}
batch.js?locale=de-DE:361 confluence-fields portal::initPortalFields()
batch.js?locale=de-DE:361 confluence-fields portal::getIssue(): jsonPayload {xsrfToken: "B4W7-X2D7-LD66-RHKC_30068a7048ecf84170fc6704fa8776f6865a9ab7_lin", user: {…}, branding: {…}, helpCenterBranding: {…}, portal: {…}, …}
batch.js?locale=de-DE:361 confluence-fields portal::initPortalFields()
batch.js?locale=de-DE:361 confluence-fields portal::getIssue(): jsonPayload {xsrfToken: "B4W7-X2D7-LD66-RHKC_30068a7048ecf84170fc6704fa8776f6865a9ab7_lin", user: {…}, branding: {…}, helpCenterBranding: {…}, portal: {…}, …}
batch.js?locale=de-DE:361 confluence-fields portal::initPortalFields()
batch.js?locale=de-DE:361 confluence-fields portal::getIssue(): jsonPayload {xsrfToken: "B4W7-X2D7-LD66-RHKC_30068a7048ecf84170fc6704fa8776f6865a9ab7_lin", user: {…}, branding: {…}, helpCenterBranding: {…}, portal: {…}, …}
batch.js?locale=de-DE:361 confluence-fields portal::initPortalFields()
batch.js?locale=de-DE:361 confluence-fields portal::getIssue(): jsonPayload {xsrfToken: "B4W7-X2D7-LD66-RHKC_30068a7048ecf84170fc6704fa8776f6865a9ab7_lin", user: {…}, branding: {…}, helpCenterBranding: {…}, portal: {…}, …}

When testing it came out that confluence custom Fields App and Extension for Jira Service Desk App cannot be activated together - if one of them is deactivated, the error is not present.
Can you also install Extension for Jira Service Desk and try to reproduce the error pleace?

Thanks!
Best Regards
Zlatica

**Comment by mesilat** [comment]
Hmm.. that's interesting. I will check that

**Comment by mesilat** [comment]
Hi,
The issue is due to the same servlet filter installed by Extensions. Please upgrade to 1.0.26 and let me know if this fixes the issue
Best regards
Vladislav

**Comment by zstetinova** [comment]
Hi Vladislav,
the issue is fixed.
Thank you!

Best Regards 
Zlatica
