### ISSUE TITLE
"Side effect" on JIRA Service Desk with this plugin.

### ISSUE THREAD

**Issue by MOEDevOps** [mesilat/confluence-fields#18]
Hi, 

We are experiencing a "side effect" with JIRA Service Desk when "Confluence Custom Fields" is activated. The URL for consulting a SD issue (i.e. https://jira.bcv.ch/jira/servicedesk/customer/portal/1/ONLINE-617) done by a user having "Service Desk Customers" role, raise the following error :
![Confluence Custom Fields error on JIRA ServiceDesk](https://user-images.githubusercontent.com/64581011/80689170-33310200-8acd-11ea-99f8-ffc6d46aae52.png)

Would you please consider this issue and give us a feedback on how to solve this problem ?

Confluence Custom Fields version : 1.0.25
JIRA version : 8.5.2
JIRA SD : 4.5.2
Browser : Chrome

Kind regards 
Philippe Martin

**Comment by mesilat** [comment]
Hi, thanks for reporting
Please upgrade to version 1.0.26 and let me know if this fixes the issue
Best regards,
Vladislav Babin

**Comment by MOEDevOps** [comment]
Fantastic ! The version 1.0.26 solve the problem ! :)
Many thanks for your quick fix !

Kind regards
Philippe Martin

**Comment by mesilat** [comment]
Thanks for your feedback
Regards,
Vladislav
