### ISSUE TITLE
Customer Portal page loads forever (spinner is displayed) due to missing XSRF token

### ISSUE THREAD

**Issue by vladmueller** [mesilat/confluence-fields#2]
Hello Mesilat,

I encounter the following issue on the customer portal when this plugin is activated:

The customer portal contains two service desk projects.
Since the second Service Desk project was created, the following problem occurs:

Steps:
* Open customer portal
* Click on a link

Expectation:
* A new page is loaded

Observation:
* A loading spinner appears
* Nothing happens
* The console log of the browser says: "Uncaught TypeError: Cannot read property 'xsrfToken' of null".
* A refresh of the page loads the desired page

Jira Version :           8.5.4
Service Desk Version: 4.5.4
Confluence Custom Fields: 1.0.26

![xsrf-1](https://user-images.githubusercontent.com/41007939/94162323-e0deec00-fe86-11ea-937b-1424f19445e9.png)

The error comes from this module in the service desk javascript:
```
/* module-key = 'com.atlassian.servicedesk.frontend-webpack-plugin:split_customerportal' .. */
```

**Comment by vb-mesilat** [comment]
Hi, Vladimir

Thanks for reporting the issue.
Please disable the **value-converter-portal-rest-filter** component of the plugin. There is a known incompatibility with some third-party plugins that prevents this component from working properly

Best regards,
Vladislav Babin
Mesilat Limited

**Comment by vladmueller** [comment]
Hi Vladislav,

thanks for your answer.
Disabling the component has helped so far 👍
