### ISSUE TITLE
batch.js error in combination with JSD 4.12.1

### ISSUE THREAD

**Issue by edwinstol** [mesilat/confluence-fields#3]
Hi - we have a situation on a Jira Service Desk instance at one of our customers when we enable your plug-in. The Portal keeps loading due to a batch.js error. What kind of information should we provide for you to triage/resolve this error?

**Comment by vb-mesilat** [comment]
Hi, thanks for reporting the issue.
There is a known incompatibility with some third-party plugins that install a servlet filter on certain SD portal endpoints. I am still working on a solution for this. Meanwhile you could disable the plugin's "value-converter-portal-filter" component to get back your customer portal.

<img width="1259" alt="Screenshot 2020-11-16 at 09 37 25" src="https://user-images.githubusercontent.com/69499122/99220265-692a9f00-27ef-11eb-95af-491d6cc9eb6d.png">

**Comment by vb-mesilat** [comment]
Hi again. Could you please upgrade to the latest version 1.0.32 and let me know if this fixes the problem?

**Comment by edwinstol** [comment]
Hi @vb-mesilat ; Thanks for your reply and quick action. We still encounter the problem on 1.0.32 with Jira Service Desk (and Refined Wiki). Disabling the 'value-converter-portal'picker' component resolves the problem (for now).

**Comment by vb-mesilat** [comment]
Hi, @edwinstol 

Could you please try this pre-release https://github.com/mesilat/confluence-fields/releases/tag/1.0.34 ?

It's a servlet filter refactoring and hopefully solves the problem, but I cannot be 100% sure as I don't have many third-party plugins in my test environment. Thank you!

**Comment by edwinstol** [comment]
Hi Vladislav,

I will try this tomorrow.

Thanks,

Edwin.

Op do 19 nov. 2020 om 10:05 schreef Vladislav Babin <
notifications@github.com>:

**Comment by vb-mesilat** [comment]
Hi, @edwinstol 

Just to inform you: there's version 1.0.35 at Atlassian Marketplace so no need to go for pre-release, just upgrade normally.
Please let me know if this fixes the issue.
There's also a docs update at https://www.mesilat.com/confluence-fields.html

Regards

Vladislav

**Comment by edwinstol** [comment]
Hi Vladislav,

Thanks. I'll test out the new version this friday.

Cheers,

Edwin.

Op di 24 nov. 2020 om 08:11 schreef Vladislav Babin <
notifications@github.com>:

**Comment by edwinstol** [comment]
Hi @vb-mesilat ,

The latest update fixed the issue. Thanks for your effort!

**Comment by vb-mesilat** [comment]
Hi, @edwinstol 

Thanks for your feedback
