### ISSUE TITLE
Clear the Confluence Field

### ISSUE THREAD

**Issue by gcuny** [mesilat/confluence-fields#3]
I would like the Confluence Field to clear automatically, if the selected options do not match the options returned by the CQL filter. This could be due a different selection or a modified input in the field referenced in the CQL filter. Your proposal in issue #2, to make this a default behaviour while keeping old field values could be enabled by some option in field settings, seems to be a good appraoch to cover this requirement.

**Comment by mesilat** [comment]
Resolved
