### ISSUE TITLE
Missing asset in 1.0.15

### ISSUE THREAD

**Issue by z720** [mesilat/confluence-fields#5]
it seems that 1.0.15 has a missing asset:
> 2019-10-10 08:33:13,846 http-nio-80-exec-22 WARN anonymous 513x291405x6 1yiwssa 10.119.207.166 /s/3e6982f472a74d339da5a6c14a8acebc-CDN/92giio/74006/be09033ea7858348cd8d5cdeb793189a/f5b5abec9c37d1422fcb90e3ee8249ba/_/download/contextbatch/js/atl.admin,jira.global,jira.admin,-_super/batch.js [webresource] error in `Content.writeTo` for com.mesilat.confluence-fields:field-configure-resources/util.js
java.lang.RuntimeException: Cannot read resource /js/util.js

And it's missing in the jar:
![image](https://user-images.githubusercontent.com/683264/66560080-ef89a180-eb56-11e9-9305-fd2125c7aebe.png)

**Comment by mesilat** [comment]
Hi, thanks for reporting
Please upgrade to version 1.0.16 This fixes the issue
