### ISSUE TITLE
I can't see the "Confluence Field" configuration option

### ISSUE THREAD

**Issue by eSailItSolutions** [mesilat/confluence-fields#7]
Hello,
I just installed the plugin and I can't see the configuration option "Confluence Field".
I have the following versions installed:
- JIRA Service Desk 4.3.0
- Jira Software 8.3.0
- Jira Core 8.3.0
- Atlassian Confluence 6.15.7

![Capture Confluence Field](https://user-images.githubusercontent.com/28733012/67384852-37b2b600-f592-11e9-8a24-dda1e1074a4b.JPG)

**Comment by babinvn** [comment]
Hi, please upgrade to version 1.0.16
This should fix the issue

**Comment by mesilat** [comment]
I guess this can be closed as no further feedback from the reporter
